#ifndef JSONMACROS_H
#define JSONMACROS_H

#include "json/json.h"

#define BEGIN_DECLARE_JSON_CLASS(NAME, PARENT_DECLARATION, ARGS) \
class NAME PARENT_DECLARATION \
{\
public:\
    NAME() {}\
    json::Object    ToObject();\
    void            FillObject(json::Object& obj);\
    std::string     Serialize();\
    void            FillMembers(const json::Object& obj);\
    static NAME     Deserialize(const json::Object& obj);\
    \
\
    ARGS

#define END_DECLARE_JSON_CLASS() };

#define DECLARE_JSON_CLASS(NAME, PARENT_DECLARATION, ARGS) \
    BEGIN_DECLARE_JSON_CLASS(NAME, PARENT_DECLARATION, ARGS) \
    END_DECLARE_JSON_CLASS()

#define DECLARE_CLASS_ARGS1(ARG1TYPE, ARG1NAME) ARG1TYPE ARG1NAME;
#define DECLARE_CLASS_ARGS2(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME) \
    DECLARE_CLASS_ARGS1(ARG1TYPE, ARG1NAME) \
    DECLARE_CLASS_ARGS1(ARG2TYPE, ARG2NAME)
#define DECLARE_CLASS_ARGS3(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME) \
    DECLARE_CLASS_ARGS2(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME) \
    DECLARE_CLASS_ARGS1(ARG3TYPE, ARG3NAME)
#define DECLARE_CLASS_ARGS4(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME) \
    DECLARE_CLASS_ARGS3(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME) \
    DECLARE_CLASS_ARGS1(ARG4TYPE, ARG4NAME)
#define DECLARE_CLASS_ARGS5(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME, ARG5TYPE, ARG5NAME) \
    DECLARE_CLASS_ARGS4(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME) \
    DECLARE_CLASS_ARGS1(ARG5TYPE, ARG5NAME)

#define DECLARE_JSON_CLASS_ARGS1(NAME, ARG1TYPE, ARG1NAME) \
    DECLARE_JSON_CLASS(NAME, , DECLARE_CLASS_ARGS1(ARG1TYPE, ARG1NAME))
#define DECLARE_JSON_CLASS_ARGS2(NAME, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME) \
    DECLARE_JSON_CLASS(NAME, , DECLARE_CLASS_ARGS2(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME))
#define DECLARE_JSON_CLASS_ARGS3(NAME, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME) \
    DECLARE_JSON_CLASS(NAME, , DECLARE_CLASS_ARGS3(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME))
#define DECLARE_JSON_CLASS_ARGS4(NAME, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME) \
    DECLARE_JSON_CLASS(NAME, , DECLARE_CLASS_ARGS4(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME))
#define DECLARE_JSON_CLASS_ARGS5(NAME, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME, ARG5TYPE, ARG5NAME) \
    DECLARE_JSON_CLASS(NAME, , DECLARE_CLASS_ARGS5(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME, ARG5TYPE, ARG5NAME))

#define DECLARE_PARENT(PARENT) : public PARENT

#define DECLARE_JSON_CHILD_CLASS_ARGS1(NAME, PARENT, ARG1TYPE, ARG1NAME) \
    DECLARE_JSON_CLASS(NAME, DECLARE_PARENT(PARENT), DECLARE_CLASS_ARGS1(ARG1TYPE, ARG1NAME))
#define DECLARE_JSON_CHILD_CLASS_ARGS2(NAME, PARENT, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME) \
    DECLARE_JSON_CLASS(NAME, DECLARE_PARENT(PARENT), DECLARE_CLASS_ARGS2(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME))
#define DECLARE_JSON_CHILD_CLASS_ARGS3(NAME, PARENT, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME) \
    DECLARE_JSON_CLASS(NAME, DECLARE_PARENT(PARENT), DECLARE_CLASS_ARGS3(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME))
#define DECLARE_JSON_CHILD_CLASS_ARGS4(NAME, PARENT, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME) \
    DECLARE_JSON_CLASS(NAME, DECLARE_PARENT(PARENT), DECLARE_CLASS_ARGS4(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME))
#define DECLARE_JSON_CHILD_CLASS_ARGS5(NAME, PARENT, ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME, ARG5TYPE, ARG5NAME) \
    DECLARE_JSON_CLASS(NAME, DECLARE_PARENT(PARENT), DECLARE_CLASS_ARGS5(ARG1TYPE, ARG1NAME, ARG2TYPE, ARG2NAME, ARG3TYPE, ARG3NAME, ARG4TYPE, ARG4NAME, ARG5TYPE, ARG5NAME))

#endif // JSONMACROS_H
